# Generated by Django 4.2.5 on 2023-11-17 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_userprofile_is_approved_alter_book_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='lost_date',
        ),
    ]
