# Generated by Django 4.2.5 on 2023-11-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_remove_rental_lost_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='returned_date',
            field=models.DateTimeField(null=True),
        ),
    ]
