# Generated by Django 4.2.4 on 2024-01-01 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0011_alter_rental_is_rental_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='is_rental_request',
        ),
    ]
