# Generated by Django 4.2.4 on 2024-01-01 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0013_rental_is_rental_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='is_rental_approved',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='is_rental_request',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='is_return_approved',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='is_return_request',
        ),
    ]
